<a href="https://colab.research.google.com/github/Simon006/python_for_data_analysis_note/blob/main/%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%9002_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy的ndarray
- > ndarray是一种多维数组对象，是一个快速而灵活的大数据集容器，它是一个通用的**同构数据多维容器**，其中的元素必须同类型，每个数组都有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数组数据类型的对象）：

- >创建数组对简单的办法就是使用np.array( )方法，输入一切序列行对象，然后产生一个新的含有传入数据的NumPy数组。

- >np.array( )会尝试为新建的数组推断出一个较为合适的数据类型。

In [ ]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

#基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少

CPU times: user 17.7 ms, sys: 6.12 ms, total: 23.8 ms
Wall time: 27.3 ms
CPU times: user 738 ms, sys: 187 ms, total: 924 ms
Wall time: 933 ms


In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
#从arr1和arr2的dtpye发现np.array()主动为数据适配数据类型

1
(5,)
float64
2
(2, 4)
int64


- > np的zeros和ones方法分别创建指定长度或形状的全零和全一数组。empty可以创建一个没有任何具体值的数组。np.empty( )会返回一些未初始化的垃圾值，认为他会返回全0数组的想法是不安全的。

In [ ]:
np.empty((2,3,2))
#显然empty输出的并不是全零值得数组

array([[[1.68502e-316, 0.00000e+000],
        [0.00000e+000, 0.00000e+000],
        [0.00000e+000, 0.00000e+000]],

       [[0.00000e+000, 0.00000e+000],
        [0.00000e+000, 0.00000e+000],
        [0.00000e+000, 0.00000e+000]]])

#ndarray
ndarray的数组如果是对二维数组单索引，那么返回行向量，对多维数组单索引，返回维度低一级的ndarray



In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0,2])
#两种等价索引方式

[7 8 9]
3
3


In [ ]:
#注意赋值中的广播机制
arr2d[0]=12
print(arr2d)

[[12 12 12]
 [ 4  5  6]
 [ 7  8  9]]


- > ndarray具有相当强大的切片功能，可以进行多维度切片索引。

In [ ]:
arr2d[:2,1:]

array([[12, 12],
       [ 5,  6]])

#花式索引
指利用证书数组进行索引


In [ ]:
arr1 = np.arange(32).reshape((8,4))
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


- >不论数组是多少维的花式索引总是一维的

In [ ]:
#花式索引
arr1[[1,5,7,2]][:,[0,3,1,2]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

- >通过下面代码我们可以更清晰的了解到花式索引是一维的是什么意思，我们单次索引只对某一个特定的维度进行，需要多维度操作的时候就需要如上式，单独对行和列进行操作，还有善用"**：**"符号进行花式索引维度的指定。

In [ ]:
a = arr1[[1,5,7,2]][[0,3,1,2]]
b = arr1[[1,5,7,2]]
print(a)
print(b)
print(a==b)


[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]
 [False False False False]]


#条件逻辑表述为数组运算
可以通过列表推导式按如下写法，但下面写法对大数组的处理不够快（所有工作由纯python完成）

In [ ]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,False,True])

result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
#注意上面的zip函数让他们变成一个字典之后再拆包就可以实现单个对应元素之间的比较了

print(result)

[1.1, 2.2, 1.3, 2.4, 1.5]


#np.where
使用np.where可以利用numpy的多维数组，使得运算速度大大提升,但需要注意的是where语法当中，将condition放在第一个参数位。

In [ ]:
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 2.4, 1.5])

再举一个例子

In [ ]:
arr1 = np.random.randn(5,6)
arr2 = np.where(arr1>0,arr1,0)
#对所有数据进行relu激活函数
print("arr1:",arr1)
print("arr2:",arr2)
print((arr1).astype(int))
print((arr2).astype(int))

arr1: [[-0.39729117 -1.65135006 -0.05192883 -0.18561128 -0.73025349 -0.04092484]
 [ 1.46547979 -0.00289345  1.22740627 -0.75631624  0.80038431  2.02204031]
 [-1.38568325 -0.22609963 -1.22903745  1.23399336 -2.04111777 -2.28187277]
 [ 1.31408043  0.47771569  1.06729681  0.77670745 -0.58168832 -0.37409586]
 [ 0.05397773  0.81200366  1.39982699 -1.2418583  -0.66324946  1.26284985]]
arr2: [[0.         0.         0.         0.         0.         0.        ]
 [1.46547979 0.         1.22740627 0.         0.80038431 2.02204031]
 [0.         0.         0.         1.23399336 0.         0.        ]
 [1.31408043 0.47771569 1.06729681 0.77670745 0.         0.        ]
 [0.05397773 0.81200366 1.39982699 0.         0.         1.26284985]]
[[ 0 -1  0  0  0  0]
 [ 1  0  1  0  0  2]
 [-1  0 -1  1 -2 -2]
 [ 1  0  1  0  0  0]
 [ 0  0  1 -1  0  1]]
[[0 0 0 0 0 0]
 [1 0 1 0 0 2]
 [0 0 0 1 0 0]
 [1 0 1 0 0 0]
 [0 0 1 0 0 1]]


In [ ]:
print(arr1.mean())
print(np.mean(arr1))
print(arr1.sum())
#sum(0)为计算每一列的和
#mean(1)为计算行的平均值

0.002416348861382193
0.002416348861382193
0.07249046584146579


#布尔值计数
利用True==1用于计数,注意元素为bool类型的数组还有all方法和any方法，分别用于检查时候所有值都是True，和测试数组中是否存在一个或多个True。

In [ ]:
arr = np.random.randn(100)
(arr>0).sum()

60

#np集合操作
针对一维ndarry的基本集合运算，最常用的是np.uniqure
- >以下两种实现方式等价，但是类型不一样

In [ ]:
ints = np.array([12,3,45,6,2,8,8,9,0,4,1,6,1,3,4,3,])
a = np.unique(ints)
print("type_a:",type(a))
print(a)
print(a[2])

b = sorted(set(ints))
print("type_b",type(b))
print(b)
print(b[2])

type_a: <class 'numpy.ndarray'>
[ 0  1  2  3  4  6  8  9 12 45]
2
type_b <class 'list'>
[0, 1, 2, 3, 4, 6, 8, 9, 12, 45]
2


#用于数组的文件输入输出
NumPy能读写磁盘上的文本数据或二进制数据。

In [ ]:
arr = np.arange(10)
np.save("s.npy",arr)
np.load("s.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- > np.savez()可以将多个数组保存到一个未压缩文件中，将数组以**关键字参数形式**传入，注意保存文件名后缀*.npz,如果需要数据压缩，可以使用numpy_savez_compressed( )

In [ ]:
arr = np.arange(10)
np.savez('s1.npz',a=arr,b=arr*2)

arch = np.load("s1.npz")
print(arch['b'])

[ 0  2  4  6  8 10 12 14 16 18]
